# server:
#   port: 8443
#   ssl:
#     key-store: ${KEY_STORE}
#     key-store-password: ${KEY_STORE_PASSWORD}
#     key-store-type: JKS
#     key-alias: mycert

# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: https://auth.certigestdev.click:8443/realms/inst_idiomas_realm
#   datasource:
#     url: ${DATABASE_URL}
#     username: ${DATABASE_USERNAME}
#     password: ${DATABASE_PASSWORD}
#     driver-class-name: com.mysql.cj.jdbc.Driver
# app:
#   cors:
#     allowed-origin: https://d16uzpy2u8y3eb.cloudfront.net
# #
# -------------------------------------------------------------------------------------------

server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/inst_idiomas_realm

  datasource:
    url: jdbc:mysql://localhost:3306/instituto_idiomas_db
    username: user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origin: http://localhost:3000
