server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/inst_idiomas_realm
  datasource:
    url: jdbc:mysql://localhost:3306/instituto_idiomas_db
    username: user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver