name: Run Tests Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job para pruebas de integración con Postman
  api-test:
    runs-on: ubuntu-latest
    needs: Course-Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/certigest-collection.json \
            -e postman/certigest-env.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html
